version: 2
jobs:
  coverage:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/palsivertsen/goutils
    steps:
      - checkout

      - run: curl -o ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -L
      - run: chmod u+x ./cc-test-reporter
      - run: go get -v -t -d ./...
      - run: go list ./... | grep -v /vendor/ | xargs -I {} bash -c "go test -coverprofile=c.out {} && ./cc-test-reporter format-coverage --output \"coverage/codeclimate.{}.json\""
      - run: ./cc-test-reporter sum-coverage --output - `find coverage -type f` | ./cc-test-reporter upload-coverage --input -
