version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/palsivertsen/goutils
    steps:
      - checkout

      - run: curl -o ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -L
      - run: chmod u+x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: go get -v -t -d ./...
      - run: go test -coverprofile=converters.out ./converters
      - run: ./cc-test-reporter after-build -t gocov --exit-code $?
